version: "3.0"
services:

  ui:
    image: ghcr.io/open-webui/open-webui:main
    restart: always
    ports:
      - 3011:8080
    volumes:
      - ./open-webui:/app/backend/data
    env_file:
      - .env
      - auto.gha.app.env
    environment:
      # - "ENABLE_SIGNUP=false"
      - "OLLAMA_BASE_URL=http://ollama:11434"
    depends_on:
      - ollama

  # ollama which should have a start command of `ollama run llama3:8b`
```‏
  ollama:
    image: ollama/ollama
    container_name: ollama
    restart: always
    ports:
      - 11434:11434
    env_file:
      - .env
      - auto.gha.app.env
    volumes:
      - ./ollama:/root/.ollama
      - ./ollama-entrypoint.sh:/ollama-entrypoint.sh  # Mount script inside container
    entrypoint: ["/bin/sh", "/ollama-entrypoint.sh"]  # Use custom entrypoint